import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed top-0 z-1 w-full bg-zinc-950 font-mono text-3xl flex flex-row justify-center">
          <a
            href="/"
            className="w-1/8 text-center border-b-4 border-transparent py-2 hover:border-[#ffa74a] transition-colors duration-150 ease-out"
          >
            yippee
          </a>
          <a
            href="/music"
            className="w-1/8 text-center border-b-4 border-transparent py-2 hover:border-[#ffa74a] transition-colors duration-150 ease-out"
          >
            my music
          </a>
          {/* <nav>
            <Link href="/" className="mx-10 w-1/6">
              yippee
            </Link>
            <Link href="/music" className="mx-10 w-1/6">
              my music
            </Link>
          </nav> */}
        </div>
        {children}
      </body>
    </html>
  );
}
